import RootLayout from "./layout.client";

export const metadata = {
  title: "Modern Bazar",
  description: "Generated by create next app",
};

export default function ServerLayout({ children }) {
  return <RootLayout>{children}</RootLayout>;
}
